const i18Obj = {
  en: {
    start: "Start",
    game: "Game",
    results: "Results",
    gallery: "Gallery",
    contacts: "Contacts",
    score: "Score:",
    "hero-text":
      "Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise",
    hire: "Hire me",
    planets_1: "Planets 1.0",
    astronauts: "Astronauts",
    planets_2: "Planets 2.0",
    stars: "Stars",
    vehicle: "Vehicle",
    cosmos: "Cosmos",
    next_round: "Next round",
    listen: "Listen to the player. Select a planet from the list.",
  },
  ru: {
    start: "Главная",
    game: "Игра",
    results: "Результаты",
    price: "Цены",
    contacts: "Контакты",
    gallery: "Галерея",
    score: "Счет:",
    hire: "Пригласить",
    planets_1: "Планеты 1.0",
    astronauts: "Астронавты",
    planets_2: "Планеты 2.0",
    stars: "Звезды",
    vehicle: "Оборудование",
    cosmos: "Космос",
    next_round: "Следующий раунд",
    listen: "Прослушайте плеер. Выберите ответ.",
  },
};
export default i18Obj;
